services:
  whatsapp-bot:
    build: .
    volumes:
      - ./wwebjs_auth:/root/.wwebjs_auth
    env_file:
      - .env
    tty: true
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"
